# Generated by Django 3.1.5 on 2021-01-19 10:07

import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(upload_to=config.utils.uuid_name_upload_to),
        ),
    ]
