# Generated by Django 3.1.5 on 2021-01-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20210120_0159'),
        ('ideas', '0002_auto_20210119_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={},
        ),
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='tools.tool'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
